languageCode = "en-US"
title = "StocksYouShouldHaveBought.com"
publishdir = "public-alt"
canonifyURLs = true
googleAnalytics = "UA-126743160-4"
baseURL = "https://youshouldhaveboughtstocks.com"
staticDir = ["static", "node_modules/@fortawesome/fontawesome-free/webfonts"]

[params]
    subtitle = "Stocks You Should Have Bought"
    description = "StocksYouShouldHaveBought.com - stocks you should have bought at IPO"
    author = "Niek van der Maas"
    favicon = "/favicon.png"

    [params.author]
        name = "Niek van der Maas"
        mail = "mail@niekvandermaas.nl"